In [86]:
import jax.numpy as jnp

In [87]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [88]:
from Systems import AutoDiffSystemModel

# Example Non-Linear System
# state space dim: 3
# control space dim: 2
# measurement space dim: 1

def f(x, u):
  return x**2 + jnp.array([
    [1, 1],
    [1, 2],
    [2, 1]
  ]) @ jnp.sqrt(u)

def h(x):
  return -2.8 * x[0,0] / x[1,0]

system = AutoDiffSystemModel(3, 2, 1, f, h)

In [89]:
x_test = jnp.array([
  [1],
  [2],
  [3]
])

u_test = jnp.array([
  [1],
  [1]
])

F_x, F_u = system.dynamics_jacobian(x_test, u_test)
H_x = system.measurement_jacobian(x_test)

print("F_x:\n", F_x)
print("F_u:\n", F_u)
print("H_x:\n", H_x)

F_x:
 [[2. 0. 0.]
 [0. 4. 0.]
 [0. 0. 6.]]
F_u:
 [[0.5 0.5]
 [0.5 1. ]
 [1.  0.5]]
H_x:
 [[-1.4  0.7  0. ]]
